<?php

use function WordPress\Filesystem\wp_join_unix_paths;

/**
 * Runtime applier for nginx + PHP-FPM (also works with Apache + PHP-FPM).
 *
 * Writes:
 * 1. {output_dir}/runtime.php — constants, server vars, route handlers
 * 2. {output_dir}/nginx.conf  — nginx server block with auto_prepend_file
 *                                and INI directives passed via fastcgi_param
 *
 * Everything lives in the output directory — nothing is written to the
 * fs-root. The nginx config passes PHP_VALUE directives to FPM via
 * fastcgi_param, which is equivalent to .user.ini but configured in one
 * place alongside the rest of the server block.
 */
class NginxFpmApplier implements RuntimeApplier
{
    /**
     * Validate literal nginx settings before writing either runtime artifact.
     *
     * @param RuntimeManifest $manifest        Source runtime settings.
     * @param string          $filesystem_root Local document root.
     * @param string          $output_dir      Directory for generated files.
     * @param array           $options {
     *     Target listener settings.
     *     @type string $host Server name; defaults to localhost.
     *     @type int    $port Listener port; defaults to 80.
     * }
     * @return string[] Setup summary and reload instructions.
     */
    public function apply(RuntimeManifest $manifest, string $filesystem_root, string $output_dir, array $options = []): array
    {
        $host = $options['host'] ?? 'localhost';
        $port = (int) ($options['port'] ?? 80);

        $summary = [];

        $runtime_path = wp_join_unix_paths($output_dir, 'runtime.php');
        foreach (['document root' => $filesystem_root, 'runtime path' => $runtime_path, 'host' => $host] as $name => $value) {
            if (preg_match('/[\x00-\x1f\x7f$]/', $value) === 1) {
                throw new InvalidArgumentException(
                    // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped -- Configuration error shown as CLI text, not HTML.
                    "Cannot use {$name} " . json_encode($value, JSON_INVALID_UTF8_SUBSTITUTE) . " in nginx configuration: dollar signs and control characters are not supported."
                );
            }
        }
        $nginx_conf = $this->generate_nginx_conf($manifest, $filesystem_root, $runtime_path, $host, $port);
        // 1. Write runtime.php
        $runtime = generate_runtime_php($manifest, $filesystem_root);
        write_runtime_file($runtime_path, $runtime);
        $summary[] = "Wrote {$runtime_path}";

        // 2. Write nginx.conf (includes auto_prepend_file + INI directives)
        $nginx_conf_path = wp_join_unix_paths($output_dir, 'nginx.conf');
        write_runtime_file($nginx_conf_path, $nginx_conf);
        $summary[] = "Wrote {$nginx_conf_path}";

        $summary[] = '';
        $summary[] = 'To use with nginx:';
        $summary[] = "  Include {$nginx_conf_path} in your nginx configuration,";
        $summary[] = '  then reload: nginx -s reload';
        $summary[] = '';
        $summary[] = 'Adjust fastcgi_pass to match your PHP-FPM socket or address.';

        return $summary;
    }

    /**
     * Generate an nginx server block that serves static files directly
     * and routes PHP requests through PHP-FPM. INI directives and
     * auto_prepend_file are passed via fastcgi_param PHP_VALUE,
     * so no .user.ini is needed in the fs-root. Literal values are quoted
     * separately from the nginx variables used for request routing.
     */
    private function generate_nginx_conf(
        RuntimeManifest $manifest,
        string $filesystem_root,
        string $runtime_path,
        string $host,
        int $port
    ): string {
        $lines = [];
        $lines[] = '# Nginx configuration — generated by apply-runtime.';
        $lines[] = '# Adjust fastcgi_pass to match your PHP-FPM socket or address.';
        $lines[] = '';
        $lines[] = 'server {';
        $lines[] = "    listen {$port};";
        $lines[] = "    server_name " . $this->quote_nginx_string($host) . ";";
        $lines[] = "    root " . $this->quote_nginx_string($filesystem_root) . ";";
        $lines[] = '    index index.php index.html;';
        $lines[] = '';
        $lines[] = '    # Static files served directly by nginx — no PHP involved.';
        $lines[] = '    location / {';
        $lines[] = '        try_files $uri $uri/ /index.php?$args;';
        $lines[] = '    }';
        $lines[] = '';
        $lines[] = '    location ~ \.php$ {';
        $lines[] = '        try_files $uri =404;';
        $lines[] = '        fastcgi_pass unix:/var/run/php-fpm.sock;';
        $lines[] = '        fastcgi_index index.php;';
        $lines[] = '        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;';
        $lines[] = '        include fastcgi_params;';
        $lines[] = '';

        // Build the PHP_VALUE string — auto_prepend_file and INI directives.
        // fastcgi_param PHP_VALUE passes these to FPM as if they were in
        // .user.ini, but without writing anything to the fs-root.
        $php_values = [];
        $php_values[] = "auto_prepend_file={$runtime_path}";
        foreach ($manifest->php_ini as $key => $value) {
            $php_values[] = "{$key}={$value}";
        }

        // PHP_VALUE accepts newline-separated directives in a single string.
        $lines[] = '        # Runtime configuration: auto_prepend_file and INI directives';
        $lines[] = '        # from the source host, passed to PHP-FPM without .user.ini.';
        $lines[] = '        fastcgi_param PHP_VALUE ' . $this->quote_nginx_string(implode("\n", $php_values)) . ';';

        $lines[] = '    }';
        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /** Keep configuration punctuation inside one nginx string argument. */
    private function quote_nginx_string(string $value): string
    {
        return '"' . strtr($value, ['\\' => '\\\\', '"' => '\\"', "\n" => '\\n', "\r" => '\\r', "\t" => '\\t']) . '"';
    }
}
